version: "3"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    entrypoint: npm run test
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27107:27107"
    logging:
      driver: none
